FROM node:18-alpine

WORKDIR /app

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ARG WATCHPACK_POLLING
ENV WATCHPACK_POLLING=${WATCHPACK_POLLING}

# Install pnpm
RUN npm install -g pnpm


# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Start development server
CMD ["pnpm", "dev"] 